// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storagepb // import "github.com/lstoll/idp/storage/storagepb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Keyspace             string               `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key                  string               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Object               *any.Any             `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *Item) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

type GetRequest struct {
	Keyspace             string   `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *GetRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{2}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Mutation struct {
	// Types that are valid to be assigned to Mutation:
	//	*Mutation_PutItem
	//	*Mutation_DeleteItem
	Mutation             isMutation_Mutation `protobuf_oneof:"mutation"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Mutation) Reset()         { *m = Mutation{} }
func (m *Mutation) String() string { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()    {}
func (*Mutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{3}
}
func (m *Mutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mutation.Unmarshal(m, b)
}
func (m *Mutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mutation.Marshal(b, m, deterministic)
}
func (dst *Mutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mutation.Merge(dst, src)
}
func (m *Mutation) XXX_Size() int {
	return xxx_messageInfo_Mutation.Size(m)
}
func (m *Mutation) XXX_DiscardUnknown() {
	xxx_messageInfo_Mutation.DiscardUnknown(m)
}

var xxx_messageInfo_Mutation proto.InternalMessageInfo

type isMutation_Mutation interface {
	isMutation_Mutation()
}

type Mutation_PutItem struct {
	PutItem *Item `protobuf:"bytes,1,opt,name=put_item,json=putItem,proto3,oneof"`
}

type Mutation_DeleteItem struct {
	DeleteItem *DeleteItem `protobuf:"bytes,2,opt,name=delete_item,json=deleteItem,proto3,oneof"`
}

func (*Mutation_PutItem) isMutation_Mutation() {}

func (*Mutation_DeleteItem) isMutation_Mutation() {}

func (m *Mutation) GetMutation() isMutation_Mutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (m *Mutation) GetPutItem() *Item {
	if x, ok := m.GetMutation().(*Mutation_PutItem); ok {
		return x.PutItem
	}
	return nil
}

func (m *Mutation) GetDeleteItem() *DeleteItem {
	if x, ok := m.GetMutation().(*Mutation_DeleteItem); ok {
		return x.DeleteItem
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Mutation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Mutation_OneofMarshaler, _Mutation_OneofUnmarshaler, _Mutation_OneofSizer, []interface{}{
		(*Mutation_PutItem)(nil),
		(*Mutation_DeleteItem)(nil),
	}
}

func _Mutation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Mutation)
	// mutation
	switch x := m.Mutation.(type) {
	case *Mutation_PutItem:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutItem); err != nil {
			return err
		}
	case *Mutation_DeleteItem:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeleteItem); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Mutation.Mutation has unexpected type %T", x)
	}
	return nil
}

func _Mutation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Mutation)
	switch tag {
	case 1: // mutation.put_item
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Item)
		err := b.DecodeMessage(msg)
		m.Mutation = &Mutation_PutItem{msg}
		return true, err
	case 2: // mutation.delete_item
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeleteItem)
		err := b.DecodeMessage(msg)
		m.Mutation = &Mutation_DeleteItem{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Mutation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Mutation)
	// mutation
	switch x := m.Mutation.(type) {
	case *Mutation_PutItem:
		s := proto.Size(x.PutItem)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Mutation_DeleteItem:
		s := proto.Size(x.DeleteItem)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DeleteItem struct {
	Keyspace             string   `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItem) Reset()         { *m = DeleteItem{} }
func (m *DeleteItem) String() string { return proto.CompactTextString(m) }
func (*DeleteItem) ProtoMessage()    {}
func (*DeleteItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{4}
}
func (m *DeleteItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItem.Unmarshal(m, b)
}
func (m *DeleteItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItem.Marshal(b, m, deterministic)
}
func (dst *DeleteItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItem.Merge(dst, src)
}
func (m *DeleteItem) XXX_Size() int {
	return xxx_messageInfo_DeleteItem.Size(m)
}
func (m *DeleteItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItem.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItem proto.InternalMessageInfo

func (m *DeleteItem) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *DeleteItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type MutateRequest struct {
	Mutations            []*Mutation `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MutateRequest) Reset()         { *m = MutateRequest{} }
func (m *MutateRequest) String() string { return proto.CompactTextString(m) }
func (*MutateRequest) ProtoMessage()    {}
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{5}
}
func (m *MutateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateRequest.Unmarshal(m, b)
}
func (m *MutateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateRequest.Marshal(b, m, deterministic)
}
func (dst *MutateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateRequest.Merge(dst, src)
}
func (m *MutateRequest) XXX_Size() int {
	return xxx_messageInfo_MutateRequest.Size(m)
}
func (m *MutateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutateRequest proto.InternalMessageInfo

func (m *MutateRequest) GetMutations() []*Mutation {
	if m != nil {
		return m.Mutations
	}
	return nil
}

type ListRequest struct {
	Keyspace             string   `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{6}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *ListRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type ListResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{7}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Bytes is a helper message for consumers that just want to persist data,
// rather than a proto message.
type Bytes struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c1bf7f30307c18ed, []int{8}
}
func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (dst *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(dst, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "lstoll.idp.storage.Item")
	proto.RegisterType((*GetRequest)(nil), "lstoll.idp.storage.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "lstoll.idp.storage.GetResponse")
	proto.RegisterType((*Mutation)(nil), "lstoll.idp.storage.Mutation")
	proto.RegisterType((*DeleteItem)(nil), "lstoll.idp.storage.DeleteItem")
	proto.RegisterType((*MutateRequest)(nil), "lstoll.idp.storage.MutateRequest")
	proto.RegisterType((*ListRequest)(nil), "lstoll.idp.storage.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "lstoll.idp.storage.ListResponse")
	proto.RegisterType((*Bytes)(nil), "lstoll.idp.storage.Bytes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Mutate is used to write to storage. If multiple items are specified and the
	// backend supports it, all actions will happen in one transaction.
	Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListKeys(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/lstoll.idp.storage.Storage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/lstoll.idp.storage.Storage/Mutate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListKeys(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/lstoll.idp.storage.Storage/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Mutate is used to write to storage. If multiple items are specified and the
	// backend supports it, all actions will happen in one transaction.
	Mutate(context.Context, *MutateRequest) (*empty.Empty, error)
	ListKeys(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lstoll.idp.storage.Storage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lstoll.idp.storage.Storage/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Mutate(ctx, req.(*MutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lstoll.idp.storage.Storage/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListKeys(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lstoll.idp.storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Storage_Get_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _Storage_Mutate_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _Storage_ListKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_c1bf7f30307c18ed) }

var fileDescriptor_storage_c1bf7f30307c18ed = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0x39, 0x49, 0xf3, 0x67, 0xdc, 0x4a, 0x3f, 0xad, 0x50, 0x65, 0x5c, 0x44, 0x8d, 0x2f,
	0x04, 0x09, 0xad, 0xa5, 0x00, 0x97, 0x0a, 0x0e, 0x09, 0x7f, 0x0a, 0x2a, 0xbd, 0x18, 0x4e, 0x5c,
	0x90, 0x1d, 0x4f, 0x83, 0xa9, 0x9d, 0x5d, 0xb2, 0x63, 0xa9, 0xfe, 0x16, 0x1c, 0xf9, 0x82, 0x7c,
	0x0f, 0xe4, 0xf5, 0x6e, 0x53, 0x35, 0x49, 0x05, 0xa7, 0xcc, 0xe6, 0xbd, 0xb7, 0xf3, 0xe6, 0xcd,
	0x1a, 0x0e, 0x14, 0x89, 0x55, 0xb2, 0x40, 0x2e, 0x57, 0x82, 0x04, 0x63, 0x85, 0x22, 0x51, 0x14,
	0x3c, 0xcf, 0x24, 0x37, 0x88, 0x7f, 0xbc, 0x10, 0x62, 0x51, 0x60, 0xa4, 0x19, 0x69, 0x75, 0x11,
	0x51, 0x5e, 0xa2, 0xa2, 0xa4, 0x94, 0xad, 0xc8, 0x3f, 0xba, 0x4d, 0xc0, 0x52, 0x52, 0x6d, 0xc0,
	0xfb, 0xb7, 0xc1, 0x64, 0x69, 0xa0, 0xf0, 0x97, 0x03, 0xbd, 0x0f, 0x84, 0x25, 0xf3, 0x61, 0x78,
	0x89, 0xb5, 0x92, 0xc9, 0x1c, 0x3d, 0x27, 0x70, 0xc6, 0xa3, 0xf8, 0xfa, 0xcc, 0xfe, 0x87, 0xee,
	0x25, 0xd6, 0x5e, 0x47, 0xff, 0xdd, 0x94, 0xec, 0x29, 0xf4, 0x45, 0xfa, 0x1d, 0xe7, 0xe4, 0x75,
	0x03, 0x67, 0xec, 0x4e, 0xee, 0xf1, 0xb6, 0x05, 0xb7, 0x2d, 0xf8, 0x74, 0x59, 0xc7, 0x86, 0xc3,
	0x9e, 0xc3, 0x00, 0xaf, 0x64, 0xbe, 0x42, 0xe5, 0xf5, 0x34, 0xdd, 0xdf, 0xa0, 0x7f, 0xb6, 0xf3,
	0xc4, 0x96, 0x1a, 0xbe, 0x04, 0x38, 0x45, 0x8a, 0xf1, 0x47, 0x85, 0x8a, 0xee, 0xf4, 0xc7, 0xa0,
	0xd7, 0xd4, 0x5e, 0x27, 0xe8, 0x8e, 0x47, 0xb1, 0xae, 0xc3, 0x57, 0xe0, 0x6a, 0xb5, 0x92, 0x62,
	0xa9, 0x90, 0x71, 0xd8, 0xcb, 0x09, 0x4b, 0xe5, 0x39, 0x41, 0x77, 0xec, 0x4e, 0x3c, 0xbe, 0x19,
	0x32, 0x6f, 0x72, 0x88, 0x5b, 0x5a, 0xf8, 0xd3, 0x81, 0xe1, 0x79, 0x45, 0x09, 0xe5, 0x62, 0xc9,
	0x5e, 0xc0, 0x50, 0x56, 0xf4, 0xb5, 0x41, 0x74, 0xef, 0x3b, 0xf4, 0xef, 0xff, 0x8b, 0x07, 0xb2,
	0x22, 0x1d, 0xe9, 0x14, 0xdc, 0x0c, 0x0b, 0x24, 0x6c, 0x95, 0x1d, 0xad, 0x7c, 0xb8, 0x4d, 0xf9,
	0x46, 0xd3, 0x8c, 0x1e, 0xb2, 0xeb, 0xd3, 0x0c, 0x60, 0x58, 0x1a, 0x17, 0xe1, 0x09, 0xc0, 0x9a,
	0xf7, 0x6f, 0xfb, 0x0a, 0xcf, 0xe0, 0x40, 0x4f, 0x83, 0x36, 0xce, 0x13, 0x18, 0xd9, 0x8b, 0x6d,
	0x26, 0x0f, 0xb6, 0x39, 0xb3, 0x19, 0xc4, 0x6b, 0x7a, 0x38, 0x05, 0xf7, 0x63, 0xae, 0xfe, 0x6a,
	0x33, 0x87, 0xd0, 0x97, 0x2b, 0xbc, 0xc8, 0xaf, 0x8c, 0x19, 0x73, 0x0a, 0x43, 0xd8, 0x6f, 0xaf,
	0x30, 0xeb, 0xb1, 0x1b, 0x74, 0x6e, 0x6c, 0xf0, 0x08, 0xf6, 0x66, 0x35, 0xa1, 0x6a, 0xc0, 0x2c,
	0xa1, 0x44, 0x5f, 0xbe, 0x1f, 0xeb, 0x7a, 0xf2, 0xdb, 0x81, 0xc1, 0xa7, 0xd6, 0x23, 0x7b, 0x07,
	0xdd, 0x53, 0x24, 0xb6, 0x35, 0xd9, 0xf5, 0x0b, 0xf2, 0x8f, 0x77, 0xe2, 0xc6, 0xc4, 0x6b, 0xe8,
	0xb7, 0x21, 0xb1, 0x47, 0x3b, 0xa3, 0xb0, 0x01, 0xfa, 0x87, 0x1b, 0x4f, 0xf8, 0x6d, 0xf3, 0xc5,
	0xb1, 0x73, 0x18, 0x36, 0x93, 0x9d, 0x61, 0xad, 0xd8, 0xd6, 0x8e, 0x37, 0xa2, 0xf3, 0x83, 0xdd,
	0x84, 0xd6, 0xd3, 0xec, 0xc9, 0x97, 0xc7, 0x8b, 0x9c, 0xbe, 0x55, 0x29, 0x9f, 0x8b, 0x32, 0x6a,
	0xd9, 0x51, 0x9e, 0xc9, 0xc8, 0xb0, 0xed, 0xaf, 0x4c, 0xd3, 0xbe, 0x76, 0xf2, 0xec, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0xb2, 0xbd, 0xf1, 0x4f, 0x04, 0x00, 0x00,
}
