// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idp.proto

package idppb // import "github.com/lstoll/idp/idppb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RefreshToken stores an oauth2 refresh token used by the oidc idp
type RefreshToken struct {
	RefreshId            string   `protobuf:"bytes,1,opt,name=refresh_id,proto3" json:"refresh_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_5863042bdd333069, []int{0}
}
func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (dst *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(dst, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetRefreshId() string {
	if m != nil {
		return m.RefreshId
	}
	return ""
}

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*RefreshToken)(nil), "idp.RefreshToken")
}

func init() { proto.RegisterFile("idp.proto", fileDescriptor_idp_5863042bdd333069) }

var fileDescriptor_idp_5863042bdd333069 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4c, 0x29, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4c, 0x29, 0x50, 0x72, 0xe1, 0xe2, 0x09, 0x4a,
	0x4d, 0x2b, 0x4a, 0x2d, 0xce, 0x08, 0xc9, 0xcf, 0x4e, 0xcd, 0x13, 0x92, 0xe3, 0xe2, 0x2a, 0x82,
	0xf0, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84, 0x44, 0xb8,
	0x58, 0x4b, 0x40, 0x0a, 0x25, 0x98, 0xc0, 0x52, 0x10, 0x8e, 0x93, 0x6c, 0x94, 0x74, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4e, 0x71, 0x49, 0x7e, 0x4e, 0x8e, 0x7e,
	0x66, 0x4a, 0x01, 0x08, 0x17, 0x24, 0x25, 0xb1, 0x81, 0x2d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x8a, 0x94, 0xa5, 0x36, 0x7d, 0x00, 0x00, 0x00,
}
