// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idp.proto

package idppb // import "github.com/lstoll/idp/idppb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RefreshToken stores an oauth2 refresh token used by the oidc idp
type RefreshToken struct {
	RefreshId            string   `protobuf:"bytes,1,opt,name=refresh_id,proto3" json:"refresh_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_db7f840132e4f690, []int{0}
}
func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (dst *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(dst, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetRefreshId() string {
	if m != nil {
		return m.RefreshId
	}
	return ""
}

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// AuthRequest represents a OAuth2 client authorization request. It holds the state
// of a single auth flow up to the point that the user authorizes the client.
type AuthRequest struct {
	// ID used to identify the authorization request.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// ID of the client requesting authorization from a user.
	ClientID string `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	// Values parsed from the initial request. These describe the resources the client is
	// requesting as well as values describing the form of the response.
	ResponseTypes []string `protobuf:"bytes,3,rep,name=response_types,json=responseTypes,proto3" json:"response_types,omitempty"`
	Scopes        []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	RedirectUri   string   `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Nonce         string   `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	State         string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	// The client has indicated that the end user must be shown an approval prompt
	// on all requests. The server cannot cache their initial action for subsequent
	// attempts.
	ForceApprovalPrompt bool                 `protobuf:"varint,8,opt,name=force_approval_prompt,json=forceApprovalPrompt,proto3" json:"force_approval_prompt,omitempty"`
	Expiry              *timestamp.Timestamp `protobuf:"bytes,9,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Has the user proved their identity through a backing identity provider?
	//
	// If false, the following fields are invalid.
	LoggedIn bool `protobuf:"varint,10,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	// The connector used to login the user and any data the connector wishes to persists.
	// Set when the user authenticates.
	ConnectorId          string   `protobuf:"bytes,11,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	ConnectorData        []byte   `protobuf:"bytes,12,opt,name=connector_data,json=connectorData,proto3" json:"connector_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_db7f840132e4f690, []int{1}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AuthRequest) GetResponseTypes() []string {
	if m != nil {
		return m.ResponseTypes
	}
	return nil
}

func (m *AuthRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *AuthRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *AuthRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthRequest) GetForceApprovalPrompt() bool {
	if m != nil {
		return m.ForceApprovalPrompt
	}
	return false
}

func (m *AuthRequest) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *AuthRequest) GetLoggedIn() bool {
	if m != nil {
		return m.LoggedIn
	}
	return false
}

func (m *AuthRequest) GetConnectorId() string {
	if m != nil {
		return m.ConnectorId
	}
	return ""
}

func (m *AuthRequest) GetConnectorData() []byte {
	if m != nil {
		return m.ConnectorData
	}
	return nil
}

func init() {
	proto.RegisterType((*RefreshToken)(nil), "idp.RefreshToken")
	proto.RegisterType((*AuthRequest)(nil), "idp.AuthRequest")
}

func init() { proto.RegisterFile("idp.proto", fileDescriptor_idp_db7f840132e4f690) }

var fileDescriptor_idp_db7f840132e4f690 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x95, 0x96, 0x2d, 0x8d, 0xdb, 0xdd, 0x83, 0xf9, 0x23, 0xab, 0x2b, 0x20, 0xac, 0x84,
	0x94, 0x53, 0x2a, 0x95, 0x4f, 0xb0, 0x90, 0x4b, 0x6e, 0x28, 0x2a, 0x17, 0x2e, 0x91, 0x1b, 0x4f,
	0x53, 0x8b, 0xd4, 0x63, 0xec, 0x09, 0x62, 0xbf, 0x08, 0x9f, 0x17, 0xd9, 0x49, 0xcb, 0x1e, 0x72,
	0x78, 0xbf, 0xf7, 0x3c, 0x9a, 0x79, 0x61, 0xa9, 0x56, 0xb6, 0xb0, 0x0e, 0x09, 0xf9, 0x5c, 0x2b,
	0xbb, 0xf9, 0xd0, 0x21, 0x76, 0x3d, 0x6c, 0x23, 0x3a, 0x0c, 0xc7, 0x2d, 0xe9, 0x33, 0x78, 0x92,
	0xe7, 0x29, 0xf5, 0x50, 0xb2, 0x75, 0x0d, 0x47, 0x07, 0xfe, 0xb4, 0xc7, 0x9f, 0x60, 0xf8, 0x7b,
	0xc6, 0xdc, 0xa8, 0x1b, 0xad, 0x44, 0x92, 0x25, 0x79, 0x5a, 0x3f, 0x23, 0xfc, 0x35, 0xbb, 0xa1,
	0x10, 0x14, 0xb3, 0x68, 0x8d, 0xe2, 0xe1, 0xef, 0x9c, 0xad, 0x1e, 0x07, 0x3a, 0xd5, 0xf0, 0x6b,
	0x00, 0x4f, 0xfc, 0x8e, 0xcd, 0xaa, 0x72, 0x7a, 0x3d, 0xab, 0x4a, 0xbe, 0x61, 0xcb, 0xaf, 0xbd,
	0x06, 0x43, 0x55, 0x39, 0x3d, 0xbc, 0x6a, 0xfe, 0x89, 0xdd, 0x39, 0xf0, 0x16, 0x8d, 0x87, 0x86,
	0x9e, 0x2c, 0x78, 0x31, 0xcf, 0xe6, 0x79, 0x5a, 0xdf, 0x5e, 0xe8, 0x3e, 0x40, 0xfe, 0x96, 0x2d,
	0x7c, 0x8b, 0xc1, 0x7e, 0x11, 0xed, 0x49, 0xf1, 0x8f, 0x6c, 0xed, 0x40, 0x69, 0x07, 0x2d, 0x35,
	0x83, 0xd3, 0xe2, 0x26, 0x8e, 0x5f, 0x5d, 0xd8, 0x77, 0xa7, 0xc3, 0xce, 0x06, 0x4d, 0x0b, 0x62,
	0x31, 0xee, 0x1c, 0x45, 0xa0, 0x9e, 0x24, 0x81, 0x78, 0x39, 0xd2, 0x28, 0xf8, 0x8e, 0xbd, 0x39,
	0xa2, 0x6b, 0xa1, 0x91, 0xd6, 0x3a, 0xfc, 0x2d, 0xfb, 0xc6, 0x3a, 0x3c, 0x5b, 0x12, 0xcb, 0x2c,
	0xc9, 0x97, 0xf5, 0xab, 0x68, 0x3e, 0x4e, 0xde, 0xb7, 0x68, 0xf1, 0x1d, 0x5b, 0xc0, 0x1f, 0xab,
	0xdd, 0x93, 0x48, 0xb3, 0x24, 0x5f, 0xed, 0x36, 0xc5, 0xd8, 0x7a, 0x71, 0x69, 0xbd, 0xd8, 0x5f,
	0x5a, 0xaf, 0xa7, 0x24, 0xbf, 0x67, 0x69, 0x8f, 0x5d, 0x07, 0xaa, 0xd1, 0x46, 0xb0, 0x38, 0x7b,
	0x39, 0x82, 0xca, 0x84, 0x9b, 0x5a, 0x34, 0x06, 0x5a, 0x42, 0x17, 0x7e, 0xc3, 0x6a, 0xbc, 0xe9,
	0xca, 0x2a, 0x15, 0x5a, 0xfb, 0x1f, 0x51, 0x92, 0xa4, 0x58, 0x67, 0x49, 0xbe, 0xae, 0x6f, 0xaf,
	0xb4, 0x94, 0x24, 0xbf, 0xbc, 0xfb, 0x71, 0xdf, 0x69, 0x3a, 0x0d, 0x87, 0xa2, 0xc5, 0xf3, 0xb6,
	0xf7, 0x84, 0x7d, 0xbf, 0xd5, 0xca, 0x86, 0xcf, 0x1e, 0x0e, 0x8b, 0xb8, 0xe1, 0xe7, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc3, 0xfb, 0x8f, 0x24, 0x37, 0x02, 0x00, 0x00,
}
