// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idp.proto

package idppb // import "github.com/lstoll/idp/idppb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Identity represents a user that was authenticated.
type Identity struct {
	// user_id is a unique identifier for this user. It should never change.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (dst *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(dst, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// OIDCAuthorization represents a successfully authenticated request
type OIDCAuthorization struct {
	Identity             *Identity            `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OIDCAuthorization) Reset()         { *m = OIDCAuthorization{} }
func (m *OIDCAuthorization) String() string { return proto.CompactTextString(m) }
func (*OIDCAuthorization) ProtoMessage()    {}
func (*OIDCAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{1}
}
func (m *OIDCAuthorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OIDCAuthorization.Unmarshal(m, b)
}
func (m *OIDCAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OIDCAuthorization.Marshal(b, m, deterministic)
}
func (dst *OIDCAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OIDCAuthorization.Merge(dst, src)
}
func (m *OIDCAuthorization) XXX_Size() int {
	return xxx_messageInfo_OIDCAuthorization.Size(m)
}
func (m *OIDCAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_OIDCAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_OIDCAuthorization proto.InternalMessageInfo

func (m *OIDCAuthorization) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *OIDCAuthorization) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

// OIDCAuthorization represents a successfully authenticated request
type SAMLAuthorization struct {
	Identity             *Identity            `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Authorized           bool                 `protobuf:"varint,2,opt,name=authorized,proto3" json:"authorized,omitempty"`
	SamlRequest          []byte               `protobuf:"bytes,3,opt,name=saml_request,json=samlRequest,proto3" json:"saml_request,omitempty"`
	RelayState           string               `protobuf:"bytes,4,opt,name=relay_state,json=relayState,proto3" json:"relay_state,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SAMLAuthorization) Reset()         { *m = SAMLAuthorization{} }
func (m *SAMLAuthorization) String() string { return proto.CompactTextString(m) }
func (*SAMLAuthorization) ProtoMessage()    {}
func (*SAMLAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{2}
}
func (m *SAMLAuthorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SAMLAuthorization.Unmarshal(m, b)
}
func (m *SAMLAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SAMLAuthorization.Marshal(b, m, deterministic)
}
func (dst *SAMLAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SAMLAuthorization.Merge(dst, src)
}
func (m *SAMLAuthorization) XXX_Size() int {
	return xxx_messageInfo_SAMLAuthorization.Size(m)
}
func (m *SAMLAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_SAMLAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_SAMLAuthorization proto.InternalMessageInfo

func (m *SAMLAuthorization) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *SAMLAuthorization) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func (m *SAMLAuthorization) GetSamlRequest() []byte {
	if m != nil {
		return m.SamlRequest
	}
	return nil
}

func (m *SAMLAuthorization) GetRelayState() string {
	if m != nil {
		return m.RelayState
	}
	return ""
}

func (m *SAMLAuthorization) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

// OIDCClient represents an oauth2 client we can oidc flow against
type OIDCClient struct {
	// Client ID and secret used to identify the client.
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// A registered set of redirect URIs. When redirecting from dex to the client, the URI
	// requested to redirect to MUST match one of these values, unless the client is "public".
	RedirectUris []string `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	// TrustedPeers are a list of peers which can issue tokens on this client's behalf using
	// the dynamic "oauth2:server:client_id:(client_id)" scope. If a peer makes such a request,
	// this client's ID will appear as the ID Token's audience.
	//
	// Clients inherently trust themselves.
	TrustedPeers []string `protobuf:"bytes,4,rep,name=trusted_peers,json=trustedPeers,proto3" json:"trusted_peers,omitempty"`
	// Public clients must use either use a redirectURL 127.0.0.1:X or "urn:ietf:wg:oauth:2.0:oob"
	Public bool `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	// Name and LogoURL used when displaying this client to the end user.
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl              string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OIDCClient) Reset()         { *m = OIDCClient{} }
func (m *OIDCClient) String() string { return proto.CompactTextString(m) }
func (*OIDCClient) ProtoMessage()    {}
func (*OIDCClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{3}
}
func (m *OIDCClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OIDCClient.Unmarshal(m, b)
}
func (m *OIDCClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OIDCClient.Marshal(b, m, deterministic)
}
func (dst *OIDCClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OIDCClient.Merge(dst, src)
}
func (m *OIDCClient) XXX_Size() int {
	return xxx_messageInfo_OIDCClient.Size(m)
}
func (m *OIDCClient) XXX_DiscardUnknown() {
	xxx_messageInfo_OIDCClient.DiscardUnknown(m)
}

var xxx_messageInfo_OIDCClient proto.InternalMessageInfo

func (m *OIDCClient) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OIDCClient) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *OIDCClient) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *OIDCClient) GetTrustedPeers() []string {
	if m != nil {
		return m.TrustedPeers
	}
	return nil
}

func (m *OIDCClient) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *OIDCClient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OIDCClient) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type WebauthnUser struct {
	// a unique identifier for this user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email  string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Groups []string `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	// AllowBootstrapEnroll indicates if we should allow users with no
	// authenticators to enroll their first with no external involvement
	AllowBootstrapEnrol  bool     `protobuf:"varint,5,opt,name=allow_bootstrap_enrol,json=allowBootstrapEnrol,proto3" json:"allow_bootstrap_enrol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebauthnUser) Reset()         { *m = WebauthnUser{} }
func (m *WebauthnUser) String() string { return proto.CompactTextString(m) }
func (*WebauthnUser) ProtoMessage()    {}
func (*WebauthnUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{4}
}
func (m *WebauthnUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebauthnUser.Unmarshal(m, b)
}
func (m *WebauthnUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebauthnUser.Marshal(b, m, deterministic)
}
func (dst *WebauthnUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebauthnUser.Merge(dst, src)
}
func (m *WebauthnUser) XXX_Size() int {
	return xxx_messageInfo_WebauthnUser.Size(m)
}
func (m *WebauthnUser) XXX_DiscardUnknown() {
	xxx_messageInfo_WebauthnUser.DiscardUnknown(m)
}

var xxx_messageInfo_WebauthnUser proto.InternalMessageInfo

func (m *WebauthnUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WebauthnUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WebauthnUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *WebauthnUser) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *WebauthnUser) GetAllowBootstrapEnrol() bool {
	if m != nil {
		return m.AllowBootstrapEnrol
	}
	return false
}

// WebauthnAuthenticator represents an authenticator device
type WebauthnAuthenticator struct {
	// user_id that this authenticator belongs to
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// webauthn data
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CredentialId         []byte   `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Aaguid               []byte   `protobuf:"bytes,5,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	SignCount            uint32   `protobuf:"varint,6,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebauthnAuthenticator) Reset()         { *m = WebauthnAuthenticator{} }
func (m *WebauthnAuthenticator) String() string { return proto.CompactTextString(m) }
func (*WebauthnAuthenticator) ProtoMessage()    {}
func (*WebauthnAuthenticator) Descriptor() ([]byte, []int) {
	return fileDescriptor_idp_446ad20ed3372739, []int{5}
}
func (m *WebauthnAuthenticator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebauthnAuthenticator.Unmarshal(m, b)
}
func (m *WebauthnAuthenticator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebauthnAuthenticator.Marshal(b, m, deterministic)
}
func (dst *WebauthnAuthenticator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebauthnAuthenticator.Merge(dst, src)
}
func (m *WebauthnAuthenticator) XXX_Size() int {
	return xxx_messageInfo_WebauthnAuthenticator.Size(m)
}
func (m *WebauthnAuthenticator) XXX_DiscardUnknown() {
	xxx_messageInfo_WebauthnAuthenticator.DiscardUnknown(m)
}

var xxx_messageInfo_WebauthnAuthenticator proto.InternalMessageInfo

func (m *WebauthnAuthenticator) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WebauthnAuthenticator) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *WebauthnAuthenticator) GetCredentialId() []byte {
	if m != nil {
		return m.CredentialId
	}
	return nil
}

func (m *WebauthnAuthenticator) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *WebauthnAuthenticator) GetAaguid() []byte {
	if m != nil {
		return m.Aaguid
	}
	return nil
}

func (m *WebauthnAuthenticator) GetSignCount() uint32 {
	if m != nil {
		return m.SignCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Identity)(nil), "idp.Identity")
	proto.RegisterType((*OIDCAuthorization)(nil), "idp.OIDCAuthorization")
	proto.RegisterType((*SAMLAuthorization)(nil), "idp.SAMLAuthorization")
	proto.RegisterType((*OIDCClient)(nil), "idp.OIDCClient")
	proto.RegisterType((*WebauthnUser)(nil), "idp.WebauthnUser")
	proto.RegisterType((*WebauthnAuthenticator)(nil), "idp.WebauthnAuthenticator")
}

func init() { proto.RegisterFile("idp.proto", fileDescriptor_idp_446ad20ed3372739) }

var fileDescriptor_idp_446ad20ed3372739 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x6a, 0xd4, 0x40,
	0x14, 0xc6, 0xc9, 0x6e, 0xbb, 0xbb, 0x39, 0xcd, 0x0a, 0x1d, 0xad, 0xc6, 0x4a, 0x6d, 0xdd, 0xde,
	0xd4, 0x9b, 0x2c, 0x54, 0x5f, 0xa0, 0xad, 0x5e, 0x2c, 0x2a, 0xca, 0xd4, 0x22, 0x78, 0x13, 0x26,
	0x99, 0x63, 0x3a, 0x38, 0xc9, 0xc4, 0xf9, 0x83, 0xae, 0xcf, 0xe1, 0xdb, 0x78, 0xed, 0x3b, 0xf8,
	0x38, 0x32, 0x93, 0xa4, 0x2e, 0x88, 0x20, 0x5e, 0x04, 0x72, 0x7e, 0x73, 0x66, 0xce, 0x77, 0x3e,
	0x3e, 0x88, 0x05, 0x6f, 0xb3, 0x56, 0x2b, 0xab, 0xc8, 0x58, 0xf0, 0x76, 0xff, 0xb0, 0x52, 0xaa,
	0x92, 0xb8, 0x0c, 0xa8, 0x70, 0x1f, 0x96, 0x56, 0xd4, 0x68, 0x2c, 0xab, 0xfb, 0xae, 0xc5, 0x31,
	0xcc, 0x56, 0x1c, 0x1b, 0x2b, 0xec, 0x9a, 0xdc, 0x83, 0xa9, 0x33, 0xa8, 0x73, 0xc1, 0xd3, 0xe8,
	0x28, 0x3a, 0x89, 0xe9, 0xc4, 0x97, 0x2b, 0xbe, 0xb0, 0xb0, 0xfb, 0x7a, 0xf5, 0xec, 0xe2, 0xcc,
	0xd9, 0x6b, 0xa5, 0xc5, 0x57, 0x66, 0x85, 0x6a, 0xc8, 0x63, 0x98, 0x89, 0xfe, 0x66, 0x68, 0xdf,
	0x39, 0x9d, 0x67, 0x7e, 0xfa, 0xf0, 0x1c, 0xbd, 0x39, 0x26, 0x4f, 0x61, 0x8a, 0x5f, 0x5a, 0xa1,
	0xd1, 0xa4, 0xa3, 0xd0, 0xb9, 0x9f, 0x75, 0xba, 0xb2, 0x41, 0x57, 0xf6, 0x76, 0xd0, 0x45, 0x87,
	0xd6, 0xc5, 0xcf, 0x08, 0x76, 0x2f, 0xcf, 0x5e, 0xbd, 0xfc, 0xef, 0xb1, 0x0f, 0x01, 0x58, 0x7f,
	0x17, 0x79, 0x98, 0x3c, 0xa3, 0x1b, 0x84, 0x3c, 0x82, 0xc4, 0xb0, 0x5a, 0xe6, 0x1a, 0x3f, 0x39,
	0x34, 0x36, 0x1d, 0x1f, 0x45, 0x27, 0x09, 0xdd, 0xf1, 0x8c, 0x76, 0x88, 0x1c, 0xc2, 0x8e, 0x46,
	0xc9, 0xd6, 0xb9, 0xb1, 0xcc, 0x62, 0xba, 0x15, 0x6c, 0x81, 0x80, 0x2e, 0x3d, 0xd9, 0x5c, 0x6d,
	0xfb, 0xdf, 0x57, 0xfb, 0x11, 0x01, 0x78, 0x47, 0x2f, 0xa4, 0xc0, 0xc6, 0x92, 0x5b, 0x30, 0xba,
	0xf1, 0x7c, 0x24, 0x38, 0xb9, 0x0b, 0x13, 0x83, 0xa5, 0x46, 0x1b, 0x44, 0xc7, 0xb4, 0xaf, 0xc8,
	0x31, 0xcc, 0x35, 0x72, 0xa1, 0xb1, 0xb4, 0xb9, 0xd3, 0xc2, 0xa4, 0xe3, 0xa3, 0xf1, 0x49, 0x4c,
	0x93, 0x01, 0x5e, 0x69, 0x61, 0x7c, 0x93, 0xd5, 0xce, 0x58, 0xe4, 0x79, 0x8b, 0xa8, 0x4d, 0xba,
	0xd5, 0x35, 0xf5, 0xf0, 0x8d, 0x67, 0x7e, 0x42, 0xeb, 0x0a, 0x29, 0xca, 0xa0, 0x7a, 0x46, 0xfb,
	0x8a, 0x10, 0xd8, 0x6a, 0x58, 0x8d, 0xe9, 0x24, 0xcc, 0x0d, 0xff, 0xe4, 0x3e, 0xcc, 0xa4, 0xaa,
	0x54, 0xee, 0xb4, 0x4c, 0xa7, 0x81, 0x4f, 0x7d, 0x7d, 0xa5, 0xe5, 0xe2, 0x5b, 0x04, 0xc9, 0x3b,
	0x2c, 0xbc, 0xa7, 0xcd, 0x95, 0x41, 0xfd, 0xc7, 0x26, 0xc3, 0x7b, 0xa3, 0x8d, 0xf7, 0xee, 0xc0,
	0x36, 0xd6, 0x4c, 0xc8, 0xe0, 0x77, 0x4c, 0xbb, 0xc2, 0x2b, 0xaa, 0xb4, 0x72, 0xed, 0xa0, 0xb7,
	0xaf, 0xc8, 0x29, 0xec, 0x31, 0x29, 0xd5, 0xe7, 0xbc, 0x50, 0xca, 0x1a, 0xab, 0x59, 0x9b, 0x63,
	0xa3, 0x95, 0xec, 0x85, 0xdf, 0x0e, 0x87, 0xe7, 0xc3, 0xd9, 0x73, 0x7f, 0xb4, 0xf8, 0x1e, 0xc1,
	0xde, 0x20, 0xcb, 0xa7, 0xc7, 0xe7, 0xa1, 0x64, 0x56, 0xe9, 0xbf, 0x46, 0xbc, 0x17, 0x3e, 0x0a,
	0x09, 0xf0, 0xc2, 0x8f, 0x61, 0x5e, 0x6a, 0x0c, 0x49, 0x62, 0xd2, 0xb7, 0x77, 0xe1, 0x48, 0x7e,
	0xc3, 0x15, 0x27, 0x07, 0x00, 0x9d, 0x6f, 0xf9, 0x47, 0x5c, 0x87, 0x70, 0x24, 0x34, 0xee, 0xc8,
	0x0b, 0x5c, 0xfb, 0x95, 0x18, 0xab, 0x9c, 0xe0, 0x41, 0x6b, 0x42, 0xfb, 0xca, 0x5f, 0x33, 0xa2,
	0x6a, 0xf2, 0x52, 0xb9, 0xc6, 0x06, 0xab, 0xe7, 0x34, 0xf6, 0xe4, 0xc2, 0x83, 0xf3, 0x83, 0xf7,
	0x0f, 0x2a, 0x61, 0xaf, 0x5d, 0x91, 0x95, 0xaa, 0x5e, 0x4a, 0x63, 0x95, 0x94, 0x4b, 0xc1, 0x5b,
	0xff, 0xb5, 0x45, 0x31, 0x09, 0xc1, 0x7a, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe6, 0x83,
	0xe2, 0xeb, 0x03, 0x00, 0x00,
}
