// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// 201901131638_create_kvstore_table.down.sql
// 201901131638_create_kvstore_table.up.sql
package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __201901131638_create_kvstore_tableDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xc8\x2e\x2b\x2e\xc9\x2f\x4a\xb5\x06\x04\x00\x00\xff\xff\x1c\x62\x72\x8e\x13\x00\x00\x00")

func _201901131638_create_kvstore_tableDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__201901131638_create_kvstore_tableDownSql,
		"201901131638_create_kvstore_table.down.sql",
	)
}

func _201901131638_create_kvstore_tableDownSql() (*asset, error) {
	bytes, err := _201901131638_create_kvstore_tableDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "201901131638_create_kvstore_table.down.sql", size: 19, mode: os.FileMode(420), modTime: time.Unix(1547419664, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __201901131638_create_kvstore_tableUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x8d\xb1\x0a\xc2\x30\x18\x84\xf7\x3c\xc5\x8d\x2d\xf4\x0d\x9c\xa2\x64\x10\x63\x95\x10\x87\x8e\x51\x0f\x0c\xa5\x36\x34\x3f\xda\xfa\xf4\xa2\xa5\x5b\xc7\xef\xee\x83\x6f\xe7\x8c\xf6\x06\x5e\x6f\xad\x41\xfb\xca\xd2\x0f\x44\xa1\x00\xa0\xe5\x94\x53\xb8\x11\xc2\x51\x50\x9f\x3c\xea\x8b\xb5\xd5\xf2\xad\xcd\xf7\x20\x01\xd7\x49\x18\x66\xe6\x98\xe2\xc0\x0c\x89\x1d\xb3\x84\x2e\xe1\x1d\xe5\xf1\x47\x7c\xfa\x27\x67\xeb\xec\xf6\x47\xed\x1a\x1c\x4c\x53\x2c\xd1\xea\x97\x28\x55\xb9\x51\xdf\x00\x00\x00\xff\xff\xe5\x5e\xfe\xd2\xa2\x00\x00\x00")

func _201901131638_create_kvstore_tableUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__201901131638_create_kvstore_tableUpSql,
		"201901131638_create_kvstore_table.up.sql",
	)
}

func _201901131638_create_kvstore_tableUpSql() (*asset, error) {
	bytes, err := _201901131638_create_kvstore_tableUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "201901131638_create_kvstore_table.up.sql", size: 162, mode: os.FileMode(420), modTime: time.Unix(1547424276, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"201901131638_create_kvstore_table.down.sql": _201901131638_create_kvstore_tableDownSql,
	"201901131638_create_kvstore_table.up.sql":   _201901131638_create_kvstore_tableUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"201901131638_create_kvstore_table.down.sql": &bintree{_201901131638_create_kvstore_tableDownSql, map[string]*bintree{}},
	"201901131638_create_kvstore_table.up.sql":   &bintree{_201901131638_create_kvstore_tableUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
