// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: init.sql

package queries

import (
	"context"
)

const selectOne = `-- name: SelectOne :one
SELECT 1
`

func (q *Queries) SelectOne(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectOne)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
