// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Credential struct {
	ID             uuid.UUID
	CredentialID   []byte
	UserID         uuid.UUID
	Name           string
	CredentialData []byte
	CreatedAt      time.Time
}

type Grant struct {
	ID            uuid.UUID
	AuthCode      []byte
	RefreshToken  []byte
	UserID        string
	ClientID      string
	GrantedScopes string
	RequestData   []byte
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

type Migration struct {
	Idx int64
	At  time.Time
}

type TinkKeyset struct {
	ID           string
	KeysetData   []byte
	MetadataData []byte
	Version      int64
}

type User struct {
	ID              uuid.UUID
	Email           string
	FullName        string
	EnrollmentKey   sql.NullString
	OverrideSubject sql.NullString
	WebauthnHandle  uuid.UUID
}

type WebSession struct {
	ID        string
	Data      []byte
	ExpiresAt string
}
