name: Chrome
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
jobs:

  integ:
    name: Chrome Integration Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1


    - name: Run Browser Integration Test
      run: |
        TEST_E2E_HEADLESS=1 go test ./e2e
